import Nav from '@/components/Nav'
import './globals.css'

export const metadata = {
  title: 'Books Ive Read',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        </body>
    </html>
  )
}
